services:
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    command: ["start-dev"]
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_URL: http://keycloak:8080
      KC_HOSTNAME_ADMIN_URL: http://keycloak:8080
      KC_PROXY: edge
    networks:
      - tb-net
    volumes:
      - keycloak_data:/opt/keycloak/data
      - /etc/localtime:/etc/localtime:ro
    restart: always

volumes:
  keycloak_data:
  
networks:
  tb-net:
    driver: bridge